<!DOCTYPE html>
<html>
<head>
    <title>見積書プレビュー</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif; /* Or a font that supports Japanese characters */
            font-size: 10pt;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .text-right {
            text-align: right;
        }
        .header, .footer {
            width: 100%;
            position: fixed;
        }
        .header {
            top: 0px;
            left: 0px;
            right: 0px;
            height: 50px;
        }
        .footer {
            bottom: 0px;
            left: 0px;
            right: 0px;
            height: 50px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>見積書</h1>
    </div>

    <div style="margin-top: 70px;">
        <h2>基本情報</h2>
        <table>
            <tr>
                <th>顧客名</th>
                <td>{{ $estimateData['customer_name'] ?? 'N/A' }}</td>
                <th>担当者</th>
                <td>{{ $estimateData['staff_name'] ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>件名</th>
                <td>{{ $estimateData['project_name'] ?? 'N/A' }}</td>
                <th>見積番号</th>
                <td>{{ $estimateData['estimate_number'] ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>発行日</th>
                <td>{{ $estimateData['issue_date'] ?? 'N/A' }}</td>
                <th>有効期限</th>
                <td>{{ $estimateData['expiry_date'] ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>支払条件</th>
                <td colspan="3">{{ $estimateData['payment_terms'] ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>納入場所</th>
                <td colspan="3">{{ $estimateData['delivery_location'] ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>備考（対外）</th>
                <td colspan="3">{{ $estimateData['external_remarks'] ?? 'N/A' }}</td>
            </tr>
        </table>

        <h2>明細</h2>
        <table>
            <thead>
                <tr>
                    <th>品目名/自由入力</th>
                    <th class="text-right">数量</th>
                    <th>単位</th>
                    <th class="text-right">単価</th>
                    <th class="text-right">金額</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($estimateData['lineItems'] ?? [] as $item)
                <tr>
                    <td>
                        {{ $item['name'] ?? 'N/A' }}
                        @if (!empty($item['description']))
                            <br><small>{{ $item['description'] }}</small>
                        @endif
                    </td>
                    <td class="text-right">{{ $item['qty'] ?? 0 }}</td>
                    <td>{{ $item['unit'] ?? 'N/A' }}</td>
                    <td class="text-right">{{ number_format($item['price'] ?? 0) }}</td>
                    <td class="text-right">{{ number_format(($item['qty'] ?? 0) * ($item['price'] ?? 0)) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div style="margin-top: 20px;">
            <p class="text-right">小計（税抜）: {{ number_format($estimateData['subtotal'] ?? 0) }}円</p>
            <p class="text-right">消費税 (10%): {{ number_format($estimateData['tax'] ?? 0) }}円</p>
            <p class="text-right"><strong>合計金額: {{ number_format($estimateData['total'] ?? 0) }}円</strong></p>
        </div>
    </div>

    <div class="footer">
        <p style="text-align: center;">Generated by Raku Estimate System</p>
    </div>
</body>
</html>